SELECT * FROM EMPLOYEE;
/
SELECT * FROM EMPLOYEE WHERE LOWER(LASTNAME)LIKE 'king%';
/
SELECT * FROM EMPLOYEE WHERE (FIRSTNAME)LIKE 'Andrew' AND (REPORTSTO)IS NULL;
/
SELECT * FROM EMPLOYEE ORDER BY (TITLE) DESC ;
/
SELECT (FIRSTNAME) FROM CUSTOMER ORDER BY (CITY)ASC;
/
INSERT INTO GENRE (GENREID,NAME)
VALUES(26,'PIANO LESSON');
/
SELECT * FROM EMPLOYEE;
/
INSERT INTO EMPLOYEE (EMPLOYEEID,LASTNAME,FIRSTNAME)
VALUES(10,'Cook','Lamar');
/
SELECT * FROM CUSTOMER;
/
INSERT INTO CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,EMAIL)
VALUES(60,'WINNER','IMA','LIVESLIFE@GMAIL');
/
INSERT INTO CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,EMAIL)
VALUES(61,'TOE','PINKY','LIVESLIFE@GMAIL');
/
SELECT * FROM CUSTOMER;
/
UPDATE CUSTOMER
SET FIRSTNAME = 'JOE',LASTNAME ='BLOW'
WHERE CUSTOMERID = 32;
/
SELECT * FROM ARTIST;
/
UPDATE ARTIST
SET NAME = 'CCR'
WHERE ARTISTID= 76;
/
SELECT * FROM INVOICE WHERE (BILLINGADDRESS) LIKE 'T%';
/
SELECT * FROM INVOICE WHERE TOTAL BETWEEN 15 AND 20;
/
SELECT * FROM EMPLOYEE WHERE HIREDATE BETWEEN '01-MAR-03'  AND '01-JUN-04';
/
SELECT * FROM CUSTOMER;
/
DELETE FROM CUSTOMER WHERE FIRSTNAME = 'ROBERT' AND LASTNAME = 'WALTER';
/
CREATE OR REPLACE PROCEDURE CURRENT_TIME_IN_OHIO AS
BEGIN
dbms_output.put_line('CURRENT TIME IN OHIO IS ' || TO_CHAR(SYSDATE, 'HH:MI:SS PM'));
END;
--DID NOT FINISH 3.3
/
--4.1
SELECT CUSTOMER.CUSTOMERID, CUSTOMER.FIRSTNAME, INVOICE.INVOICEID
FROM INVOICE
INNER JOIN Customer ON INVOICE.CustomerID = Customer.CustomerID;
/
SELECT Invoice.Total, Invoice.Invoiceid, Customer.Firstname, Customer.Lastname
FROM CUSTOMER
FULL OUTER JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID;
--THIS ONE DID NOT WORK FOR OUTER JOIN
/
SELECT ARTIST.NAME, ALBUM.TITLE
FROM ARTIST
RIGHT OUTER JOIN ALBUM ON ARTIST.ARTISTID = ALBUM.ALBUMID;
/
SELECT ARTIST.NAME, ALBUM.TITLE
FROM ALBUM
CROSS JOIN ARTIST ORDER BY ARTIST.NAME;
/
SELECT * FROM EMPLOYEE;
SELECT EMPLOYEE.EMPLOYEEID, EMPLOYEE.REPORTSTO 
FROM EMPLOYEE
WHERE EMPLOYEE.EMPLOYEEID <> EMPLOYEE.REPORTSTO;